apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

images:
  - name: ghcr.io/hadv/quant-backfill
    newName: ghcr.io/hadv/quant-backfill
    newTag: v1.0.0 # Dòng này sẽ được GitHub Actions tự động update khi deploy
